<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.quarkiverse.multitenancy</groupId>
        <artifactId>quarkus-multitenancy-parent</artifactId>
        <version>0.2.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>quarkus-multitenancy-docs</artifactId>
    <packaging>pom</packaging>
    <name>Quarkus Multitenancy - Documentation</name>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>quarkus-multitenancy-core-deployment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>quarkus-multitenancy-http-deployment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>quarkus-multitenancy-messaging-kafka-deployment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>quarkus-multitenancy-orm-deployment</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-config-doc-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <targetDirectory>${project.build.directory}/generated-docs/</targetDirectory>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
